# netlify.toml

# Build settings
[build]
  base = "./" # Path to your build output directory, if needed
  functions = "functions" # Path to the directory containing serverless functions

# HTTP headers configuration
[[headers]]
  # Define headers for all pages and assets
  for = "/*"
    [headers.values]
      # Add any headers you need here, e.g., Cache-Control, Content-Security-Policy, etc.
      Cache-Control = "public, max-age=3600"

# Redirects configuration
[[redirects]]
  # Define redirects for specific paths
  from = "/old-path"
  to = "/new-path"
  status = 301 # Use the appropriate HTTP status code

# Additional redirects can be added as needed
# ...

# Function specific settings
# You can specify settings for individual functions if needed
# [[functions]]
#   name = "functionName"
#   command = "path/to/custom/function/script.js"
#   runtime = "nodejs14.x" # Specify the Node.js runtime version

# Environment variables
# You can define environment variables here, which can be accessed in your functions
# [build.environment]
#   MY_API_KEY = "your-api-key"

# Deploy settings
[build.environment]
  # Specify environment variables for the build process, if needed
  NODE_VERSION = "14" # Specify the Node.js version for the build environment

# Branch specific settings (if needed)
# [context.production]
#   command = "npm run build:production"

# Plugins (if you use any Netlify plugins)
# [[plugins]]
#   package = "netlify-plugin-name"
#   # Plugin-specific configuration
#   # ...

# Deploy contexts (if needed)
# [context.branch-deploy]
#   command = "npm run build:branch"
#   # ...

# Notifications (if you want to receive deployment notifications)
# [notifications]
#   # Slack notifications, email notifications, etc.
#   # ...

# Build hooks (if you want to trigger specific actions on build)
# [[hooks]]
#   id = "custom-build-hook"
#   command = "npm run custom-build-action"
#   # ...
